
CREATE TABLE `MANAGER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LOGIN` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ROLES` tinyblob,
  `VERSION` bigint(20)  DEFAULT 1,
  `CREATION_DATETIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `MODIFICATION_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT manager_unique UNIQUE (`LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
